layout_spectrum: 0.5441808617384275
typography_spectrum: 0.4246220310193735
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.7386090341556153
  lightness: 0.41617632241735214
  saturation: 0.11499338647212354
  rhythmicContrast: 0.8989453672367784
content_rating:
  adult: false
opengraph:
  type: ''
  appId: ''
author:
  name: Joao Oliveira
  url: ''
  email: joao@nicolauoliveira.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c93bbf7b-9f36-4bf3-bea2-a6d605483bdc.jpg
name: Olive Computations
navigation:
  - name: Your Money Aggregator
    url: >-
      https://chrome.google.com/webstore/detail/your-money-aggregator/pkhbgealgppobjjkeahfgknimjonelkn?hl=en
    type: external
  - name: Online Shopping Aggregator
    id: 15ab9a07-c121-4bc4-80ac-159dd54b055f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3dbe698a-3471-4e8e-b746-338e52d6326c.jpg
title: Olive Computations
description: Reactive & Scalable Software
purpose:
  - type: internal
    label: Online Shopping Aggregator
    item: 15ab9a07-c121-4bc4-80ac-159dd54b055f
  - type: contact
    url: 'mailto:joao@nicolauoliveira.com'
    label: Contact me
content: []
url: 'http://olivecomputations.com'
github: true
