typography_spectrum: 0.981828194556684
content_rating:
  adult: false
color:
  brandColors:
    - '#010101'
    - '#5E5E60'
    - '#868686'
    - '#FFFFFF'
    - '#D9D9DB'
  brandStrength: 0.4372347250246065
  lightness: 0.6009682181609407
  saturation: 0.10299366610355233
  rhythmicContrast: 0.4432093881486482
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.45303237091307297
author:
  name: Joao Oliveira
  url: 'https://www.linkedin.com/in/jnicolau/'
  email: joao@nicolauoliveira.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c93bbf7b-9f36-4bf3-bea2-a6d605483bdc.jpg
name: Olive Computations
url: 'http://olivecomputations.com'
navigation:
  - name: Your Money Aggregator
    url: >-
      https://chrome.google.com/webstore/detail/your-money-aggregator/pkhbgealgppobjjkeahfgknimjonelkn?hl=en
    type: external
  - name: Online Shopping Aggregator
    id: 15ab9a07-c121-4bc4-80ac-159dd54b055f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3dbe698a-3471-4e8e-b746-338e52d6326c.jpg
title: Olive Computations
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7666d8d-5364-4120-b1c7-e1a1196e1ba3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7666d8d-5364-4120-b1c7-e1a1196e1ba3.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Reactive & Scalable Software
purpose:
  - type: internal
    label: Online Shopping Aggregator
    item: 15ab9a07-c121-4bc4-80ac-159dd54b055f
  - type: external
    url: 'https://www.linkedin.com/in/jnicolau/'
    label: LinkedIn
